### ISSUE TITLE
This page contains the following errors:  error on line 2 at column 6: XML declaration allowed only at the start of the document Below is a rendering of the page up to the first error.

### ISSUE THREAD

**Issue by jericopulvera** [jailtonsc/laravel-response-xml#11]
This page contains the following errors:

error on line 2 at column 6: XML declaration allowed only at the start of the document
Below is a rendering of the page up to the first error.

**Comment by jericopulvera** [comment]
This error happens when you put the controller inside the api.php instead of web.php

**Comment by jailtonsc** [comment]
Hello,
Were you able to solve the problem?
