### ISSUE TITLE
How do you change the <row_0> <row_1> to model name?

### ISSUE THREAD

**Issue by jericopulvera** [jailtonsc/laravel-response-xml#12]
How do you change the row_0 row_1 to model name?

**Comment by jailtonsc** [comment]
By the position of the record in the array, example if it is the position zero, it becomes row_0 and if it is the postion one it becomes row_1.

**Comment by jailtonsc** [comment]
Sorry for the delay, I did the integration with the @roblesterjr04 code and I ended up forgetting to generate a version teg note.

The problem has already been fixed.
