### ISSUE TITLE
xml version and encoding

### ISSUE THREAD

**Issue by ellgibug** [jailtonsc/laravel-response-xml#14]
Hello!

Thanks for your package. 
I need to display `<?xml version="1.0" encoding="UTF-8"?>`
before the response. I've tried to change `'template' => '<?xml version="1.0" encoding="UTF-8"?><response></response>',` in the config file after publishing, but nothing happens.

Is there any way to echo in on the page? Thanks for help)

**Comment by ellgibug** [comment]
@jailtonsc thank you ;)

**Comment by jailtonsc** [comment]
Hello, 
I made the adjustments. I put a new attribute in the configuration file that tells the encoding

**Comment by ellgibug** [comment]
@jailtonsc Wow, thank you very much!!!
