### ISSUE TITLE
What about Laravel 5.4

### ISSUE THREAD

**Issue by LiderParking** [jailtonsc/laravel-response-xml#5]
same as in topic

**Comment by jailtonsc** [comment]
I'm going to check if the code already runs on laravel 5.4, if it does not run I'll make that adjustment.

**Comment by timhaak** [comment]
After applying path https://github.com/jailtonsc/laravel-response-xml/pull/4

It's working on laravel 5.4 for me

**Comment by jailtonsc** [comment]
Sorry for the delay. Thanks for the contribution I already include in the package.
